spring:
  application:
    name: freindshipbe

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    # Uncomment for local database connection
    # url: jdbc:mysql://localhost:3306/freindship
    # username: springstudent
    # password: springstudent

    # Uncomment for another local database connection
    # url: jdbc:mysql://localhost:3307/mydb
    # initialize: true
    # initialization-mode: always

    # Uncomment for a production database
    # url: jdbc:mysql://db:3306/mydb
    username: root
    password: password

  redis:
    host: redis
    port: 6379
    password: password
    timeout: 2000
    jedis:
      pool:
        max-wait: 10000ms
        max-active: 10

  data:
    rest:
      base-path: /magic-api

  doc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
    show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8081
    servlet:
      context-path: /actuator

logging:
  level:
    org:
      hibernate:
        SQL: debug
#        orm:
#          jdbc:
#            bind: trace
      springframework: DEBUG
    com:
      levdevs:
        freindshipbe: DEBUG
    #root: DEBUG
    # Uncomment for trace logging
    # root: trace
    # org.springframework: trace
