version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      AWS_PROFILE: friendship
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    volumes:
      - ~/.aws:/root/.aws  # Mount your local AWS credentials to the container
    depends_on:
      - db
#      - redis

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
#  redis:
#    image: redis:latest
#    container_name: redis
#    restart: always
#    ports:
#      - "6379:6379"
#    environment:
#      REDIS_PASSWORD: password # Optional, only if you want to use a password
#    command: ["redis-server", "--requirepass", "password"] # Enabling password authentication
#    healthcheck:
#      test: [ "CMD", "redis-cli", "-h", "localhost", "-a", "password", "PING" ]
#      interval: 30s
#      retries: 3
#      start_period: 10s
#      timeout: 10s